<?php $categories = $this->getMenuItems(); ?>
<?php if($categories && count($categories) > 0):?>
    <div class="box box-cms-menu">
        <div class="box-title"><?php echo Mage::getStoreConfig('cmsmenu/general/menu_title')?></div>
        <ul id="cms-menu">
        <?php foreach($categories as $_category):?>
            <li class="cms-menu-item <?php echo $this->getPageState($_category['identifier']); ?>">
                <a href="<?php echo $this->getCmsPageUrl($_category['identifier'])?>"><?php echo $_category['title']; ?></a>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

